/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/dns/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDomainAttachments implements DomainAttachmentInterface
type FakeDomainAttachments struct {
	Fake *FakeDnsV1alpha1
	ns   string
}

var domainattachmentsResource = schema.GroupVersionResource{Group: "dns.alicloud.kubeform.com", Version: "v1alpha1", Resource: "domainattachments"}

var domainattachmentsKind = schema.GroupVersionKind{Group: "dns.alicloud.kubeform.com", Version: "v1alpha1", Kind: "DomainAttachment"}

// Get takes name of the domainAttachment, and returns the corresponding domainAttachment object, and an error if there is any.
func (c *FakeDomainAttachments) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(domainattachmentsResource, c.ns, name), &v1alpha1.DomainAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainAttachment), err
}

// List takes label and field selectors, and returns the list of DomainAttachments that match those selectors.
func (c *FakeDomainAttachments) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainAttachmentList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(domainattachmentsResource, domainattachmentsKind, c.ns, opts), &v1alpha1.DomainAttachmentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DomainAttachmentList{ListMeta: obj.(*v1alpha1.DomainAttachmentList).ListMeta}
	for _, item := range obj.(*v1alpha1.DomainAttachmentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested domainAttachments.
func (c *FakeDomainAttachments) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(domainattachmentsResource, c.ns, opts))

}

// Create takes the representation of a domainAttachment and creates it.  Returns the server's representation of the domainAttachment, and an error, if there is any.
func (c *FakeDomainAttachments) Create(ctx context.Context, domainAttachment *v1alpha1.DomainAttachment, opts v1.CreateOptions) (result *v1alpha1.DomainAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(domainattachmentsResource, c.ns, domainAttachment), &v1alpha1.DomainAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainAttachment), err
}

// Update takes the representation of a domainAttachment and updates it. Returns the server's representation of the domainAttachment, and an error, if there is any.
func (c *FakeDomainAttachments) Update(ctx context.Context, domainAttachment *v1alpha1.DomainAttachment, opts v1.UpdateOptions) (result *v1alpha1.DomainAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(domainattachmentsResource, c.ns, domainAttachment), &v1alpha1.DomainAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainAttachment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDomainAttachments) UpdateStatus(ctx context.Context, domainAttachment *v1alpha1.DomainAttachment, opts v1.UpdateOptions) (*v1alpha1.DomainAttachment, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(domainattachmentsResource, "status", c.ns, domainAttachment), &v1alpha1.DomainAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainAttachment), err
}

// Delete takes name of the domainAttachment and deletes it. Returns an error if one occurs.
func (c *FakeDomainAttachments) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(domainattachmentsResource, c.ns, name), &v1alpha1.DomainAttachment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDomainAttachments) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(domainattachmentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DomainAttachmentList{})
	return err
}

// Patch applies the patch and returns the patched domainAttachment.
func (c *FakeDomainAttachments) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainAttachment, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(domainattachmentsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DomainAttachment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainAttachment), err
}
