/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cdn/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDomainNews implements DomainNewInterface
type FakeDomainNews struct {
	Fake *FakeCdnV1alpha1
	ns   string
}

var domainnewsResource = schema.GroupVersionResource{Group: "cdn.alicloud.kubeform.com", Version: "v1alpha1", Resource: "domainnews"}

var domainnewsKind = schema.GroupVersionKind{Group: "cdn.alicloud.kubeform.com", Version: "v1alpha1", Kind: "DomainNew"}

// Get takes name of the domainNew, and returns the corresponding domainNew object, and an error if there is any.
func (c *FakeDomainNews) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainNew, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(domainnewsResource, c.ns, name), &v1alpha1.DomainNew{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainNew), err
}

// List takes label and field selectors, and returns the list of DomainNews that match those selectors.
func (c *FakeDomainNews) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainNewList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(domainnewsResource, domainnewsKind, c.ns, opts), &v1alpha1.DomainNewList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DomainNewList{ListMeta: obj.(*v1alpha1.DomainNewList).ListMeta}
	for _, item := range obj.(*v1alpha1.DomainNewList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested domainNews.
func (c *FakeDomainNews) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(domainnewsResource, c.ns, opts))

}

// Create takes the representation of a domainNew and creates it.  Returns the server's representation of the domainNew, and an error, if there is any.
func (c *FakeDomainNews) Create(ctx context.Context, domainNew *v1alpha1.DomainNew, opts v1.CreateOptions) (result *v1alpha1.DomainNew, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(domainnewsResource, c.ns, domainNew), &v1alpha1.DomainNew{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainNew), err
}

// Update takes the representation of a domainNew and updates it. Returns the server's representation of the domainNew, and an error, if there is any.
func (c *FakeDomainNews) Update(ctx context.Context, domainNew *v1alpha1.DomainNew, opts v1.UpdateOptions) (result *v1alpha1.DomainNew, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(domainnewsResource, c.ns, domainNew), &v1alpha1.DomainNew{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainNew), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDomainNews) UpdateStatus(ctx context.Context, domainNew *v1alpha1.DomainNew, opts v1.UpdateOptions) (*v1alpha1.DomainNew, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(domainnewsResource, "status", c.ns, domainNew), &v1alpha1.DomainNew{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainNew), err
}

// Delete takes name of the domainNew and deletes it. Returns an error if one occurs.
func (c *FakeDomainNews) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(domainnewsResource, c.ns, name), &v1alpha1.DomainNew{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDomainNews) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(domainnewsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DomainNewList{})
	return err
}

// Patch applies the patch and returns the patched domainNew.
func (c *FakeDomainNews) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainNew, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(domainnewsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DomainNew{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainNew), err
}
