/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/alidns/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAccessStrategies implements AccessStrategyInterface
type FakeAccessStrategies struct {
	Fake *FakeAlidnsV1alpha1
	ns   string
}

var accessstrategiesResource = schema.GroupVersionResource{Group: "alidns.alicloud.kubeform.com", Version: "v1alpha1", Resource: "accessstrategies"}

var accessstrategiesKind = schema.GroupVersionKind{Group: "alidns.alicloud.kubeform.com", Version: "v1alpha1", Kind: "AccessStrategy"}

// Get takes name of the accessStrategy, and returns the corresponding accessStrategy object, and an error if there is any.
func (c *FakeAccessStrategies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.AccessStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(accessstrategiesResource, c.ns, name), &v1alpha1.AccessStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessStrategy), err
}

// List takes label and field selectors, and returns the list of AccessStrategies that match those selectors.
func (c *FakeAccessStrategies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.AccessStrategyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(accessstrategiesResource, accessstrategiesKind, c.ns, opts), &v1alpha1.AccessStrategyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AccessStrategyList{ListMeta: obj.(*v1alpha1.AccessStrategyList).ListMeta}
	for _, item := range obj.(*v1alpha1.AccessStrategyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested accessStrategies.
func (c *FakeAccessStrategies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(accessstrategiesResource, c.ns, opts))

}

// Create takes the representation of a accessStrategy and creates it.  Returns the server's representation of the accessStrategy, and an error, if there is any.
func (c *FakeAccessStrategies) Create(ctx context.Context, accessStrategy *v1alpha1.AccessStrategy, opts v1.CreateOptions) (result *v1alpha1.AccessStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(accessstrategiesResource, c.ns, accessStrategy), &v1alpha1.AccessStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessStrategy), err
}

// Update takes the representation of a accessStrategy and updates it. Returns the server's representation of the accessStrategy, and an error, if there is any.
func (c *FakeAccessStrategies) Update(ctx context.Context, accessStrategy *v1alpha1.AccessStrategy, opts v1.UpdateOptions) (result *v1alpha1.AccessStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(accessstrategiesResource, c.ns, accessStrategy), &v1alpha1.AccessStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessStrategy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAccessStrategies) UpdateStatus(ctx context.Context, accessStrategy *v1alpha1.AccessStrategy, opts v1.UpdateOptions) (*v1alpha1.AccessStrategy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(accessstrategiesResource, "status", c.ns, accessStrategy), &v1alpha1.AccessStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessStrategy), err
}

// Delete takes name of the accessStrategy and deletes it. Returns an error if one occurs.
func (c *FakeAccessStrategies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(accessstrategiesResource, c.ns, name), &v1alpha1.AccessStrategy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAccessStrategies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(accessstrategiesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.AccessStrategyList{})
	return err
}

// Patch applies the patch and returns the patched accessStrategy.
func (c *FakeAccessStrategies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.AccessStrategy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(accessstrategiesResource, c.ns, name, pt, data, subresources...), &v1alpha1.AccessStrategy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AccessStrategy), err
}
