/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/ess/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeScalinggroupVserverGroupses implements ScalinggroupVserverGroupsInterface
type FakeScalinggroupVserverGroupses struct {
	Fake *FakeEssV1alpha1
	ns   string
}

var scalinggroupvservergroupsesResource = schema.GroupVersionResource{Group: "ess.alicloud.kubeform.com", Version: "v1alpha1", Resource: "scalinggroupvservergroupses"}

var scalinggroupvservergroupsesKind = schema.GroupVersionKind{Group: "ess.alicloud.kubeform.com", Version: "v1alpha1", Kind: "ScalinggroupVserverGroups"}

// Get takes name of the scalinggroupVserverGroups, and returns the corresponding scalinggroupVserverGroups object, and an error if there is any.
func (c *FakeScalinggroupVserverGroupses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ScalinggroupVserverGroups, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(scalinggroupvservergroupsesResource, c.ns, name), &v1alpha1.ScalinggroupVserverGroups{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScalinggroupVserverGroups), err
}

// List takes label and field selectors, and returns the list of ScalinggroupVserverGroupses that match those selectors.
func (c *FakeScalinggroupVserverGroupses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ScalinggroupVserverGroupsList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(scalinggroupvservergroupsesResource, scalinggroupvservergroupsesKind, c.ns, opts), &v1alpha1.ScalinggroupVserverGroupsList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ScalinggroupVserverGroupsList{ListMeta: obj.(*v1alpha1.ScalinggroupVserverGroupsList).ListMeta}
	for _, item := range obj.(*v1alpha1.ScalinggroupVserverGroupsList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested scalinggroupVserverGroupses.
func (c *FakeScalinggroupVserverGroupses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(scalinggroupvservergroupsesResource, c.ns, opts))

}

// Create takes the representation of a scalinggroupVserverGroups and creates it.  Returns the server's representation of the scalinggroupVserverGroups, and an error, if there is any.
func (c *FakeScalinggroupVserverGroupses) Create(ctx context.Context, scalinggroupVserverGroups *v1alpha1.ScalinggroupVserverGroups, opts v1.CreateOptions) (result *v1alpha1.ScalinggroupVserverGroups, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(scalinggroupvservergroupsesResource, c.ns, scalinggroupVserverGroups), &v1alpha1.ScalinggroupVserverGroups{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScalinggroupVserverGroups), err
}

// Update takes the representation of a scalinggroupVserverGroups and updates it. Returns the server's representation of the scalinggroupVserverGroups, and an error, if there is any.
func (c *FakeScalinggroupVserverGroupses) Update(ctx context.Context, scalinggroupVserverGroups *v1alpha1.ScalinggroupVserverGroups, opts v1.UpdateOptions) (result *v1alpha1.ScalinggroupVserverGroups, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(scalinggroupvservergroupsesResource, c.ns, scalinggroupVserverGroups), &v1alpha1.ScalinggroupVserverGroups{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScalinggroupVserverGroups), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeScalinggroupVserverGroupses) UpdateStatus(ctx context.Context, scalinggroupVserverGroups *v1alpha1.ScalinggroupVserverGroups, opts v1.UpdateOptions) (*v1alpha1.ScalinggroupVserverGroups, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(scalinggroupvservergroupsesResource, "status", c.ns, scalinggroupVserverGroups), &v1alpha1.ScalinggroupVserverGroups{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScalinggroupVserverGroups), err
}

// Delete takes name of the scalinggroupVserverGroups and deletes it. Returns an error if one occurs.
func (c *FakeScalinggroupVserverGroupses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(scalinggroupvservergroupsesResource, c.ns, name), &v1alpha1.ScalinggroupVserverGroups{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeScalinggroupVserverGroupses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(scalinggroupvservergroupsesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ScalinggroupVserverGroupsList{})
	return err
}

// Patch applies the patch and returns the patched scalinggroupVserverGroups.
func (c *FakeScalinggroupVserverGroupses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ScalinggroupVserverGroups, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(scalinggroupvservergroupsesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ScalinggroupVserverGroups{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ScalinggroupVserverGroups), err
}
