/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/router/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeInterfaceConnections implements InterfaceConnectionInterface
type FakeInterfaceConnections struct {
	Fake *FakeRouterV1alpha1
	ns   string
}

var interfaceconnectionsResource = schema.GroupVersionResource{Group: "router.alicloud.kubeform.com", Version: "v1alpha1", Resource: "interfaceconnections"}

var interfaceconnectionsKind = schema.GroupVersionKind{Group: "router.alicloud.kubeform.com", Version: "v1alpha1", Kind: "InterfaceConnection"}

// Get takes name of the interfaceConnection, and returns the corresponding interfaceConnection object, and an error if there is any.
func (c *FakeInterfaceConnections) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.InterfaceConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(interfaceconnectionsResource, c.ns, name), &v1alpha1.InterfaceConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InterfaceConnection), err
}

// List takes label and field selectors, and returns the list of InterfaceConnections that match those selectors.
func (c *FakeInterfaceConnections) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.InterfaceConnectionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(interfaceconnectionsResource, interfaceconnectionsKind, c.ns, opts), &v1alpha1.InterfaceConnectionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.InterfaceConnectionList{ListMeta: obj.(*v1alpha1.InterfaceConnectionList).ListMeta}
	for _, item := range obj.(*v1alpha1.InterfaceConnectionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested interfaceConnections.
func (c *FakeInterfaceConnections) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(interfaceconnectionsResource, c.ns, opts))

}

// Create takes the representation of a interfaceConnection and creates it.  Returns the server's representation of the interfaceConnection, and an error, if there is any.
func (c *FakeInterfaceConnections) Create(ctx context.Context, interfaceConnection *v1alpha1.InterfaceConnection, opts v1.CreateOptions) (result *v1alpha1.InterfaceConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(interfaceconnectionsResource, c.ns, interfaceConnection), &v1alpha1.InterfaceConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InterfaceConnection), err
}

// Update takes the representation of a interfaceConnection and updates it. Returns the server's representation of the interfaceConnection, and an error, if there is any.
func (c *FakeInterfaceConnections) Update(ctx context.Context, interfaceConnection *v1alpha1.InterfaceConnection, opts v1.UpdateOptions) (result *v1alpha1.InterfaceConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(interfaceconnectionsResource, c.ns, interfaceConnection), &v1alpha1.InterfaceConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InterfaceConnection), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeInterfaceConnections) UpdateStatus(ctx context.Context, interfaceConnection *v1alpha1.InterfaceConnection, opts v1.UpdateOptions) (*v1alpha1.InterfaceConnection, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(interfaceconnectionsResource, "status", c.ns, interfaceConnection), &v1alpha1.InterfaceConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InterfaceConnection), err
}

// Delete takes name of the interfaceConnection and deletes it. Returns an error if one occurs.
func (c *FakeInterfaceConnections) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(interfaceconnectionsResource, c.ns, name), &v1alpha1.InterfaceConnection{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeInterfaceConnections) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(interfaceconnectionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.InterfaceConnectionList{})
	return err
}

// Patch applies the patch and returns the patched interfaceConnection.
func (c *FakeInterfaceConnections) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.InterfaceConnection, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(interfaceconnectionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.InterfaceConnection{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.InterfaceConnection), err
}
