/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/ddoscoo/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSchedulerRules implements SchedulerRuleInterface
type FakeSchedulerRules struct {
	Fake *FakeDdoscooV1alpha1
	ns   string
}

var schedulerrulesResource = schema.GroupVersionResource{Group: "ddoscoo.alicloud.kubeform.com", Version: "v1alpha1", Resource: "schedulerrules"}

var schedulerrulesKind = schema.GroupVersionKind{Group: "ddoscoo.alicloud.kubeform.com", Version: "v1alpha1", Kind: "SchedulerRule"}

// Get takes name of the schedulerRule, and returns the corresponding schedulerRule object, and an error if there is any.
func (c *FakeSchedulerRules) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SchedulerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(schedulerrulesResource, c.ns, name), &v1alpha1.SchedulerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchedulerRule), err
}

// List takes label and field selectors, and returns the list of SchedulerRules that match those selectors.
func (c *FakeSchedulerRules) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SchedulerRuleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(schedulerrulesResource, schedulerrulesKind, c.ns, opts), &v1alpha1.SchedulerRuleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SchedulerRuleList{ListMeta: obj.(*v1alpha1.SchedulerRuleList).ListMeta}
	for _, item := range obj.(*v1alpha1.SchedulerRuleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested schedulerRules.
func (c *FakeSchedulerRules) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(schedulerrulesResource, c.ns, opts))

}

// Create takes the representation of a schedulerRule and creates it.  Returns the server's representation of the schedulerRule, and an error, if there is any.
func (c *FakeSchedulerRules) Create(ctx context.Context, schedulerRule *v1alpha1.SchedulerRule, opts v1.CreateOptions) (result *v1alpha1.SchedulerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(schedulerrulesResource, c.ns, schedulerRule), &v1alpha1.SchedulerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchedulerRule), err
}

// Update takes the representation of a schedulerRule and updates it. Returns the server's representation of the schedulerRule, and an error, if there is any.
func (c *FakeSchedulerRules) Update(ctx context.Context, schedulerRule *v1alpha1.SchedulerRule, opts v1.UpdateOptions) (result *v1alpha1.SchedulerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(schedulerrulesResource, c.ns, schedulerRule), &v1alpha1.SchedulerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchedulerRule), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSchedulerRules) UpdateStatus(ctx context.Context, schedulerRule *v1alpha1.SchedulerRule, opts v1.UpdateOptions) (*v1alpha1.SchedulerRule, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(schedulerrulesResource, "status", c.ns, schedulerRule), &v1alpha1.SchedulerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchedulerRule), err
}

// Delete takes name of the schedulerRule and deletes it. Returns an error if one occurs.
func (c *FakeSchedulerRules) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(schedulerrulesResource, c.ns, name), &v1alpha1.SchedulerRule{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSchedulerRules) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(schedulerrulesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SchedulerRuleList{})
	return err
}

// Patch applies the patch and returns the patched schedulerRule.
func (c *FakeSchedulerRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SchedulerRule, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schedulerrulesResource, c.ns, name, pt, data, subresources...), &v1alpha1.SchedulerRule{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SchedulerRule), err
}
