/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cloud/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSsoUsers implements SsoUserInterface
type FakeSsoUsers struct {
	Fake *FakeCloudV1alpha1
	ns   string
}

var ssousersResource = schema.GroupVersionResource{Group: "cloud.alicloud.kubeform.com", Version: "v1alpha1", Resource: "ssousers"}

var ssousersKind = schema.GroupVersionKind{Group: "cloud.alicloud.kubeform.com", Version: "v1alpha1", Kind: "SsoUser"}

// Get takes name of the ssoUser, and returns the corresponding ssoUser object, and an error if there is any.
func (c *FakeSsoUsers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.SsoUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(ssousersResource, c.ns, name), &v1alpha1.SsoUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsoUser), err
}

// List takes label and field selectors, and returns the list of SsoUsers that match those selectors.
func (c *FakeSsoUsers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SsoUserList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(ssousersResource, ssousersKind, c.ns, opts), &v1alpha1.SsoUserList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SsoUserList{ListMeta: obj.(*v1alpha1.SsoUserList).ListMeta}
	for _, item := range obj.(*v1alpha1.SsoUserList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ssoUsers.
func (c *FakeSsoUsers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(ssousersResource, c.ns, opts))

}

// Create takes the representation of a ssoUser and creates it.  Returns the server's representation of the ssoUser, and an error, if there is any.
func (c *FakeSsoUsers) Create(ctx context.Context, ssoUser *v1alpha1.SsoUser, opts v1.CreateOptions) (result *v1alpha1.SsoUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(ssousersResource, c.ns, ssoUser), &v1alpha1.SsoUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsoUser), err
}

// Update takes the representation of a ssoUser and updates it. Returns the server's representation of the ssoUser, and an error, if there is any.
func (c *FakeSsoUsers) Update(ctx context.Context, ssoUser *v1alpha1.SsoUser, opts v1.UpdateOptions) (result *v1alpha1.SsoUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(ssousersResource, c.ns, ssoUser), &v1alpha1.SsoUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsoUser), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSsoUsers) UpdateStatus(ctx context.Context, ssoUser *v1alpha1.SsoUser, opts v1.UpdateOptions) (*v1alpha1.SsoUser, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(ssousersResource, "status", c.ns, ssoUser), &v1alpha1.SsoUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsoUser), err
}

// Delete takes name of the ssoUser and deletes it. Returns an error if one occurs.
func (c *FakeSsoUsers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(ssousersResource, c.ns, name), &v1alpha1.SsoUser{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSsoUsers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(ssousersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SsoUserList{})
	return err
}

// Patch applies the patch and returns the patched ssoUser.
func (c *FakeSsoUsers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.SsoUser, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(ssousersResource, c.ns, name, pt, data, subresources...), &v1alpha1.SsoUser{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.SsoUser), err
}
