/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/bastionhost/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeHostGroups implements HostGroupInterface
type FakeHostGroups struct {
	Fake *FakeBastionhostV1alpha1
	ns   string
}

var hostgroupsResource = schema.GroupVersionResource{Group: "bastionhost.alicloud.kubeform.com", Version: "v1alpha1", Resource: "hostgroups"}

var hostgroupsKind = schema.GroupVersionKind{Group: "bastionhost.alicloud.kubeform.com", Version: "v1alpha1", Kind: "HostGroup"}

// Get takes name of the hostGroup, and returns the corresponding hostGroup object, and an error if there is any.
func (c *FakeHostGroups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(hostgroupsResource, c.ns, name), &v1alpha1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostGroup), err
}

// List takes label and field selectors, and returns the list of HostGroups that match those selectors.
func (c *FakeHostGroups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.HostGroupList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(hostgroupsResource, hostgroupsKind, c.ns, opts), &v1alpha1.HostGroupList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.HostGroupList{ListMeta: obj.(*v1alpha1.HostGroupList).ListMeta}
	for _, item := range obj.(*v1alpha1.HostGroupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested hostGroups.
func (c *FakeHostGroups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(hostgroupsResource, c.ns, opts))

}

// Create takes the representation of a hostGroup and creates it.  Returns the server's representation of the hostGroup, and an error, if there is any.
func (c *FakeHostGroups) Create(ctx context.Context, hostGroup *v1alpha1.HostGroup, opts v1.CreateOptions) (result *v1alpha1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(hostgroupsResource, c.ns, hostGroup), &v1alpha1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostGroup), err
}

// Update takes the representation of a hostGroup and updates it. Returns the server's representation of the hostGroup, and an error, if there is any.
func (c *FakeHostGroups) Update(ctx context.Context, hostGroup *v1alpha1.HostGroup, opts v1.UpdateOptions) (result *v1alpha1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(hostgroupsResource, c.ns, hostGroup), &v1alpha1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostGroup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeHostGroups) UpdateStatus(ctx context.Context, hostGroup *v1alpha1.HostGroup, opts v1.UpdateOptions) (*v1alpha1.HostGroup, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(hostgroupsResource, "status", c.ns, hostGroup), &v1alpha1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostGroup), err
}

// Delete takes name of the hostGroup and deletes it. Returns an error if one occurs.
func (c *FakeHostGroups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(hostgroupsResource, c.ns, name), &v1alpha1.HostGroup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeHostGroups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(hostgroupsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.HostGroupList{})
	return err
}

// Patch applies the patch and returns the patched hostGroup.
func (c *FakeHostGroups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HostGroup, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(hostgroupsResource, c.ns, name, pt, data, subresources...), &v1alpha1.HostGroup{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.HostGroup), err
}
