/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cen/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTransitRouters implements TransitRouterInterface
type FakeTransitRouters struct {
	Fake *FakeCenV1alpha1
	ns   string
}

var transitroutersResource = schema.GroupVersionResource{Group: "cen.alicloud.kubeform.com", Version: "v1alpha1", Resource: "transitrouters"}

var transitroutersKind = schema.GroupVersionKind{Group: "cen.alicloud.kubeform.com", Version: "v1alpha1", Kind: "TransitRouter"}

// Get takes name of the transitRouter, and returns the corresponding transitRouter object, and an error if there is any.
func (c *FakeTransitRouters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TransitRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(transitroutersResource, c.ns, name), &v1alpha1.TransitRouter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouter), err
}

// List takes label and field selectors, and returns the list of TransitRouters that match those selectors.
func (c *FakeTransitRouters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TransitRouterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(transitroutersResource, transitroutersKind, c.ns, opts), &v1alpha1.TransitRouterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TransitRouterList{ListMeta: obj.(*v1alpha1.TransitRouterList).ListMeta}
	for _, item := range obj.(*v1alpha1.TransitRouterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested transitRouters.
func (c *FakeTransitRouters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(transitroutersResource, c.ns, opts))

}

// Create takes the representation of a transitRouter and creates it.  Returns the server's representation of the transitRouter, and an error, if there is any.
func (c *FakeTransitRouters) Create(ctx context.Context, transitRouter *v1alpha1.TransitRouter, opts v1.CreateOptions) (result *v1alpha1.TransitRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(transitroutersResource, c.ns, transitRouter), &v1alpha1.TransitRouter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouter), err
}

// Update takes the representation of a transitRouter and updates it. Returns the server's representation of the transitRouter, and an error, if there is any.
func (c *FakeTransitRouters) Update(ctx context.Context, transitRouter *v1alpha1.TransitRouter, opts v1.UpdateOptions) (result *v1alpha1.TransitRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(transitroutersResource, c.ns, transitRouter), &v1alpha1.TransitRouter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouter), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTransitRouters) UpdateStatus(ctx context.Context, transitRouter *v1alpha1.TransitRouter, opts v1.UpdateOptions) (*v1alpha1.TransitRouter, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(transitroutersResource, "status", c.ns, transitRouter), &v1alpha1.TransitRouter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouter), err
}

// Delete takes name of the transitRouter and deletes it. Returns an error if one occurs.
func (c *FakeTransitRouters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(transitroutersResource, c.ns, name), &v1alpha1.TransitRouter{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTransitRouters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(transitroutersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TransitRouterList{})
	return err
}

// Patch applies the patch and returns the patched transitRouter.
func (c *FakeTransitRouters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TransitRouter, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(transitroutersResource, c.ns, name, pt, data, subresources...), &v1alpha1.TransitRouter{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouter), err
}
