/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cen/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTransitRouterRouteEntries implements TransitRouterRouteEntryInterface
type FakeTransitRouterRouteEntries struct {
	Fake *FakeCenV1alpha1
	ns   string
}

var transitrouterrouteentriesResource = schema.GroupVersionResource{Group: "cen.alicloud.kubeform.com", Version: "v1alpha1", Resource: "transitrouterrouteentries"}

var transitrouterrouteentriesKind = schema.GroupVersionKind{Group: "cen.alicloud.kubeform.com", Version: "v1alpha1", Kind: "TransitRouterRouteEntry"}

// Get takes name of the transitRouterRouteEntry, and returns the corresponding transitRouterRouteEntry object, and an error if there is any.
func (c *FakeTransitRouterRouteEntries) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TransitRouterRouteEntry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(transitrouterrouteentriesResource, c.ns, name), &v1alpha1.TransitRouterRouteEntry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouterRouteEntry), err
}

// List takes label and field selectors, and returns the list of TransitRouterRouteEntries that match those selectors.
func (c *FakeTransitRouterRouteEntries) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TransitRouterRouteEntryList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(transitrouterrouteentriesResource, transitrouterrouteentriesKind, c.ns, opts), &v1alpha1.TransitRouterRouteEntryList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TransitRouterRouteEntryList{ListMeta: obj.(*v1alpha1.TransitRouterRouteEntryList).ListMeta}
	for _, item := range obj.(*v1alpha1.TransitRouterRouteEntryList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested transitRouterRouteEntries.
func (c *FakeTransitRouterRouteEntries) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(transitrouterrouteentriesResource, c.ns, opts))

}

// Create takes the representation of a transitRouterRouteEntry and creates it.  Returns the server's representation of the transitRouterRouteEntry, and an error, if there is any.
func (c *FakeTransitRouterRouteEntries) Create(ctx context.Context, transitRouterRouteEntry *v1alpha1.TransitRouterRouteEntry, opts v1.CreateOptions) (result *v1alpha1.TransitRouterRouteEntry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(transitrouterrouteentriesResource, c.ns, transitRouterRouteEntry), &v1alpha1.TransitRouterRouteEntry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouterRouteEntry), err
}

// Update takes the representation of a transitRouterRouteEntry and updates it. Returns the server's representation of the transitRouterRouteEntry, and an error, if there is any.
func (c *FakeTransitRouterRouteEntries) Update(ctx context.Context, transitRouterRouteEntry *v1alpha1.TransitRouterRouteEntry, opts v1.UpdateOptions) (result *v1alpha1.TransitRouterRouteEntry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(transitrouterrouteentriesResource, c.ns, transitRouterRouteEntry), &v1alpha1.TransitRouterRouteEntry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouterRouteEntry), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeTransitRouterRouteEntries) UpdateStatus(ctx context.Context, transitRouterRouteEntry *v1alpha1.TransitRouterRouteEntry, opts v1.UpdateOptions) (*v1alpha1.TransitRouterRouteEntry, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(transitrouterrouteentriesResource, "status", c.ns, transitRouterRouteEntry), &v1alpha1.TransitRouterRouteEntry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouterRouteEntry), err
}

// Delete takes name of the transitRouterRouteEntry and deletes it. Returns an error if one occurs.
func (c *FakeTransitRouterRouteEntries) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(transitrouterrouteentriesResource, c.ns, name), &v1alpha1.TransitRouterRouteEntry{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTransitRouterRouteEntries) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(transitrouterrouteentriesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TransitRouterRouteEntryList{})
	return err
}

// Patch applies the patch and returns the patched transitRouterRouteEntry.
func (c *FakeTransitRouterRouteEntries) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TransitRouterRouteEntry, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(transitrouterrouteentriesResource, c.ns, name, pt, data, subresources...), &v1alpha1.TransitRouterRouteEntry{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TransitRouterRouteEntry), err
}
