/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/scdn/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDomainConfigs implements DomainConfigInterface
type FakeDomainConfigs struct {
	Fake *FakeScdnV1alpha1
	ns   string
}

var domainconfigsResource = schema.GroupVersionResource{Group: "scdn.alicloud.kubeform.com", Version: "v1alpha1", Resource: "domainconfigs"}

var domainconfigsKind = schema.GroupVersionKind{Group: "scdn.alicloud.kubeform.com", Version: "v1alpha1", Kind: "DomainConfig"}

// Get takes name of the domainConfig, and returns the corresponding domainConfig object, and an error if there is any.
func (c *FakeDomainConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DomainConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(domainconfigsResource, c.ns, name), &v1alpha1.DomainConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainConfig), err
}

// List takes label and field selectors, and returns the list of DomainConfigs that match those selectors.
func (c *FakeDomainConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DomainConfigList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(domainconfigsResource, domainconfigsKind, c.ns, opts), &v1alpha1.DomainConfigList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DomainConfigList{ListMeta: obj.(*v1alpha1.DomainConfigList).ListMeta}
	for _, item := range obj.(*v1alpha1.DomainConfigList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested domainConfigs.
func (c *FakeDomainConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(domainconfigsResource, c.ns, opts))

}

// Create takes the representation of a domainConfig and creates it.  Returns the server's representation of the domainConfig, and an error, if there is any.
func (c *FakeDomainConfigs) Create(ctx context.Context, domainConfig *v1alpha1.DomainConfig, opts v1.CreateOptions) (result *v1alpha1.DomainConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(domainconfigsResource, c.ns, domainConfig), &v1alpha1.DomainConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainConfig), err
}

// Update takes the representation of a domainConfig and updates it. Returns the server's representation of the domainConfig, and an error, if there is any.
func (c *FakeDomainConfigs) Update(ctx context.Context, domainConfig *v1alpha1.DomainConfig, opts v1.UpdateOptions) (result *v1alpha1.DomainConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(domainconfigsResource, c.ns, domainConfig), &v1alpha1.DomainConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainConfig), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDomainConfigs) UpdateStatus(ctx context.Context, domainConfig *v1alpha1.DomainConfig, opts v1.UpdateOptions) (*v1alpha1.DomainConfig, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(domainconfigsResource, "status", c.ns, domainConfig), &v1alpha1.DomainConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainConfig), err
}

// Delete takes name of the domainConfig and deletes it. Returns an error if one occurs.
func (c *FakeDomainConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(domainconfigsResource, c.ns, name), &v1alpha1.DomainConfig{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDomainConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(domainconfigsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DomainConfigList{})
	return err
}

// Patch applies the patch and returns the patched domainConfig.
func (c *FakeDomainConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DomainConfig, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(domainconfigsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DomainConfig{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DomainConfig), err
}
