/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/yundun/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeBastionhostInstances implements BastionhostInstanceInterface
type FakeBastionhostInstances struct {
	Fake *FakeYundunV1alpha1
	ns   string
}

var bastionhostinstancesResource = schema.GroupVersionResource{Group: "yundun.alicloud.kubeform.com", Version: "v1alpha1", Resource: "bastionhostinstances"}

var bastionhostinstancesKind = schema.GroupVersionKind{Group: "yundun.alicloud.kubeform.com", Version: "v1alpha1", Kind: "BastionhostInstance"}

// Get takes name of the bastionhostInstance, and returns the corresponding bastionhostInstance object, and an error if there is any.
func (c *FakeBastionhostInstances) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BastionhostInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(bastionhostinstancesResource, c.ns, name), &v1alpha1.BastionhostInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BastionhostInstance), err
}

// List takes label and field selectors, and returns the list of BastionhostInstances that match those selectors.
func (c *FakeBastionhostInstances) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BastionhostInstanceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(bastionhostinstancesResource, bastionhostinstancesKind, c.ns, opts), &v1alpha1.BastionhostInstanceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BastionhostInstanceList{ListMeta: obj.(*v1alpha1.BastionhostInstanceList).ListMeta}
	for _, item := range obj.(*v1alpha1.BastionhostInstanceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested bastionhostInstances.
func (c *FakeBastionhostInstances) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(bastionhostinstancesResource, c.ns, opts))

}

// Create takes the representation of a bastionhostInstance and creates it.  Returns the server's representation of the bastionhostInstance, and an error, if there is any.
func (c *FakeBastionhostInstances) Create(ctx context.Context, bastionhostInstance *v1alpha1.BastionhostInstance, opts v1.CreateOptions) (result *v1alpha1.BastionhostInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(bastionhostinstancesResource, c.ns, bastionhostInstance), &v1alpha1.BastionhostInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BastionhostInstance), err
}

// Update takes the representation of a bastionhostInstance and updates it. Returns the server's representation of the bastionhostInstance, and an error, if there is any.
func (c *FakeBastionhostInstances) Update(ctx context.Context, bastionhostInstance *v1alpha1.BastionhostInstance, opts v1.UpdateOptions) (result *v1alpha1.BastionhostInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(bastionhostinstancesResource, c.ns, bastionhostInstance), &v1alpha1.BastionhostInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BastionhostInstance), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeBastionhostInstances) UpdateStatus(ctx context.Context, bastionhostInstance *v1alpha1.BastionhostInstance, opts v1.UpdateOptions) (*v1alpha1.BastionhostInstance, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(bastionhostinstancesResource, "status", c.ns, bastionhostInstance), &v1alpha1.BastionhostInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BastionhostInstance), err
}

// Delete takes name of the bastionhostInstance and deletes it. Returns an error if one occurs.
func (c *FakeBastionhostInstances) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(bastionhostinstancesResource, c.ns, name), &v1alpha1.BastionhostInstance{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeBastionhostInstances) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(bastionhostinstancesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.BastionhostInstanceList{})
	return err
}

// Patch applies the patch and returns the patched bastionhostInstance.
func (c *FakeBastionhostInstances) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BastionhostInstance, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(bastionhostinstancesResource, c.ns, name, pt, data, subresources...), &v1alpha1.BastionhostInstance{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BastionhostInstance), err
}
