apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: alicloud.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: listeners.alb.alicloud.kubeform.com
spec:
  group: alb.alicloud.kubeform.com
  names:
    kind: Listener
    listKind: ListenerList
    plural: listeners
    singular: listener
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  accessLogRecordCustomizedHeadersEnabled:
                    type: boolean
                  accessLogTracingConfig:
                    properties:
                      tracingEnabled:
                        type: boolean
                      tracingSample:
                        format: int64
                        type: integer
                      tracingType:
                        type: string
                    type: object
                  aclConfig:
                    properties:
                      aclRelations:
                        items:
                          properties:
                            aclID:
                              type: string
                            status:
                              type: string
                          type: object
                        type: array
                      aclType:
                        type: string
                    type: object
                  certificates:
                    items:
                      properties:
                        certificateID:
                          type: string
                      type: object
                    type: array
                  defaultActions:
                    items:
                      properties:
                        forwardGroupConfig:
                          properties:
                            serverGroupTuples:
                              items:
                                properties:
                                  serverGroupID:
                                    type: string
                                required:
                                - serverGroupID
                                type: object
                              type: array
                          required:
                          - serverGroupTuples
                          type: object
                        type:
                          type: string
                      required:
                      - forwardGroupConfig
                      - type
                      type: object
                    type: array
                  dryRun:
                    type: boolean
                  gzipEnabled:
                    type: boolean
                  http2Enabled:
                    type: boolean
                  id:
                    type: string
                  idleTimeout:
                    format: int64
                    type: integer
                  listenerDescription:
                    type: string
                  listenerPort:
                    format: int64
                    type: integer
                  listenerProtocol:
                    type: string
                  loadBalancerID:
                    type: string
                  quicConfig:
                    properties:
                      quicListenerID:
                        type: string
                      quicUpgradeEnabled:
                        type: boolean
                    type: object
                  requestTimeout:
                    format: int64
                    type: integer
                  securityPolicyID:
                    type: string
                  status:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  xforwardedForConfig:
                    properties:
                      xforwardedforclientcertIssuerdnalias:
                        type: string
                      xforwardedforclientcertIssuerdnenabled:
                        type: boolean
                      xforwardedforclientcertclientverifyalias:
                        type: string
                      xforwardedforclientcertclientverifyenabled:
                        type: boolean
                      xforwardedforclientcertfingerprintalias:
                        type: string
                      xforwardedforclientcertfingerprintenabled:
                        type: boolean
                      xforwardedforclientcertsubjectdnalias:
                        type: string
                      xforwardedforclientcertsubjectdnenabled:
                        type: boolean
                      xforwardedforclientsrcportenabled:
                        type: boolean
                      xforwardedforenabled:
                        type: boolean
                      xforwardedforprotoenabled:
                        type: boolean
                      xforwardedforslbidenabled:
                        type: boolean
                      xforwardedforslbportenabled:
                        type: boolean
                    type: object
                required:
                - listenerPort
                - listenerProtocol
                - loadBalancerID
                type: object
              state:
                properties:
                  accessLogRecordCustomizedHeadersEnabled:
                    type: boolean
                  accessLogTracingConfig:
                    properties:
                      tracingEnabled:
                        type: boolean
                      tracingSample:
                        format: int64
                        type: integer
                      tracingType:
                        type: string
                    type: object
                  aclConfig:
                    properties:
                      aclRelations:
                        items:
                          properties:
                            aclID:
                              type: string
                            status:
                              type: string
                          type: object
                        type: array
                      aclType:
                        type: string
                    type: object
                  certificates:
                    items:
                      properties:
                        certificateID:
                          type: string
                      type: object
                    type: array
                  defaultActions:
                    items:
                      properties:
                        forwardGroupConfig:
                          properties:
                            serverGroupTuples:
                              items:
                                properties:
                                  serverGroupID:
                                    type: string
                                required:
                                - serverGroupID
                                type: object
                              type: array
                          required:
                          - serverGroupTuples
                          type: object
                        type:
                          type: string
                      required:
                      - forwardGroupConfig
                      - type
                      type: object
                    type: array
                  dryRun:
                    type: boolean
                  gzipEnabled:
                    type: boolean
                  http2Enabled:
                    type: boolean
                  id:
                    type: string
                  idleTimeout:
                    format: int64
                    type: integer
                  listenerDescription:
                    type: string
                  listenerPort:
                    format: int64
                    type: integer
                  listenerProtocol:
                    type: string
                  loadBalancerID:
                    type: string
                  quicConfig:
                    properties:
                      quicListenerID:
                        type: string
                      quicUpgradeEnabled:
                        type: boolean
                    type: object
                  requestTimeout:
                    format: int64
                    type: integer
                  securityPolicyID:
                    type: string
                  status:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  xforwardedForConfig:
                    properties:
                      xforwardedforclientcertIssuerdnalias:
                        type: string
                      xforwardedforclientcertIssuerdnenabled:
                        type: boolean
                      xforwardedforclientcertclientverifyalias:
                        type: string
                      xforwardedforclientcertclientverifyenabled:
                        type: boolean
                      xforwardedforclientcertfingerprintalias:
                        type: string
                      xforwardedforclientcertfingerprintenabled:
                        type: boolean
                      xforwardedforclientcertsubjectdnalias:
                        type: string
                      xforwardedforclientcertsubjectdnenabled:
                        type: boolean
                      xforwardedforclientsrcportenabled:
                        type: boolean
                      xforwardedforenabled:
                        type: boolean
                      xforwardedforprotoenabled:
                        type: boolean
                      xforwardedforslbidenabled:
                        type: boolean
                      xforwardedforslbportenabled:
                        type: boolean
                    type: object
                required:
                - listenerPort
                - listenerProtocol
                - loadBalancerID
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
