apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: alicloud.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: instances.db.alicloud.kubeform.com
spec:
  group: db.alicloud.kubeform.com
  names:
    kind: Instance
    listKind: InstanceList
    plural: instances
    singular: instance
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  acl:
                    type: string
                  autoRenew:
                    type: boolean
                  autoRenewPeriod:
                    format: int64
                    type: integer
                  autoUpgradeMinorVersion:
                    type: string
                  caType:
                    type: string
                  clientCaCert:
                    type: string
                  clientCaEnabled:
                    format: int64
                    type: integer
                  clientCertRevocationList:
                    type: string
                  clientCrlEnabled:
                    format: int64
                    type: integer
                  connectionString:
                    type: string
                  connectionStringPrefix:
                    type: string
                  dbInstanceIPArrayAttribute:
                    type: string
                  dbInstanceIPArrayName:
                    type: string
                  dbInstanceStorageType:
                    type: string
                  encryptionKey:
                    type: string
                  engine:
                    type: string
                  engineVersion:
                    type: string
                  forceRestart:
                    type: boolean
                  haConfig:
                    type: string
                  id:
                    type: string
                  instanceChargeType:
                    type: string
                  instanceName:
                    type: string
                  instanceStorage:
                    format: int64
                    type: integer
                  instanceType:
                    type: string
                  maintainTime:
                    type: string
                  manualHaTime:
                    type: string
                  modifyMode:
                    type: string
                  monitoringPeriod:
                    format: int64
                    type: integer
                  parameters:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  period:
                    format: int64
                    type: integer
                  port:
                    type: string
                  privateIPAddress:
                    type: string
                  replicationACL:
                    type: string
                  resourceGroupID:
                    type: string
                  securityGroupID:
                    description: Deprecated
                    type: string
                  securityGroupIDS:
                    items:
                      type: string
                    type: array
                  securityIPMode:
                    type: string
                  securityIPS:
                    items:
                      type: string
                    type: array
                  securityIPType:
                    type: string
                  serverCert:
                    type: string
                  serverKey:
                    type: string
                  sqlCollectorConfigValue:
                    format: int64
                    type: integer
                  sqlCollectorStatus:
                    type: string
                  sslAction:
                    type: string
                  sslStatus:
                    type: string
                  switchTime:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  targetMinorVersion:
                    type: string
                  tdeStatus:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  upgradeDbInstanceKernelVersion:
                    type: boolean
                  upgradeTime:
                    type: string
                  vswitchID:
                    type: string
                  whitelistNetworkType:
                    type: string
                  zoneID:
                    type: string
                  zoneIDSlaveA:
                    type: string
                  zoneIDSlaveB:
                    type: string
                required:
                - engine
                - engineVersion
                - instanceStorage
                - instanceType
                type: object
              state:
                properties:
                  acl:
                    type: string
                  autoRenew:
                    type: boolean
                  autoRenewPeriod:
                    format: int64
                    type: integer
                  autoUpgradeMinorVersion:
                    type: string
                  caType:
                    type: string
                  clientCaCert:
                    type: string
                  clientCaEnabled:
                    format: int64
                    type: integer
                  clientCertRevocationList:
                    type: string
                  clientCrlEnabled:
                    format: int64
                    type: integer
                  connectionString:
                    type: string
                  connectionStringPrefix:
                    type: string
                  dbInstanceIPArrayAttribute:
                    type: string
                  dbInstanceIPArrayName:
                    type: string
                  dbInstanceStorageType:
                    type: string
                  encryptionKey:
                    type: string
                  engine:
                    type: string
                  engineVersion:
                    type: string
                  forceRestart:
                    type: boolean
                  haConfig:
                    type: string
                  id:
                    type: string
                  instanceChargeType:
                    type: string
                  instanceName:
                    type: string
                  instanceStorage:
                    format: int64
                    type: integer
                  instanceType:
                    type: string
                  maintainTime:
                    type: string
                  manualHaTime:
                    type: string
                  modifyMode:
                    type: string
                  monitoringPeriod:
                    format: int64
                    type: integer
                  parameters:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  period:
                    format: int64
                    type: integer
                  port:
                    type: string
                  privateIPAddress:
                    type: string
                  replicationACL:
                    type: string
                  resourceGroupID:
                    type: string
                  securityGroupID:
                    description: Deprecated
                    type: string
                  securityGroupIDS:
                    items:
                      type: string
                    type: array
                  securityIPMode:
                    type: string
                  securityIPS:
                    items:
                      type: string
                    type: array
                  securityIPType:
                    type: string
                  serverCert:
                    type: string
                  serverKey:
                    type: string
                  sqlCollectorConfigValue:
                    format: int64
                    type: integer
                  sqlCollectorStatus:
                    type: string
                  sslAction:
                    type: string
                  sslStatus:
                    type: string
                  switchTime:
                    type: string
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  targetMinorVersion:
                    type: string
                  tdeStatus:
                    type: string
                  timeouts:
                    properties:
                      create:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      default:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      delete:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      read:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                      update:
                        description: A Duration represents the elapsed time between
                          two instants as an int64 nanosecond count. The representation
                          limits the largest representable duration to approximately
                          290 years.
                        format: int64
                        type: integer
                    type: object
                  upgradeDbInstanceKernelVersion:
                    type: boolean
                  upgradeTime:
                    type: string
                  vswitchID:
                    type: string
                  whitelistNetworkType:
                    type: string
                  zoneID:
                    type: string
                  zoneIDSlaveA:
                    type: string
                  zoneIDSlaveB:
                    type: string
                required:
                - engine
                - engineVersion
                - instanceStorage
                - instanceType
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
