apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: alicloud.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: launchtemplates.ecs.alicloud.kubeform.com
spec:
  group: ecs.alicloud.kubeform.com
  names:
    kind: LaunchTemplate
    listKind: LaunchTemplateList
    plural: launchtemplates
    singular: launchtemplate
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  autoReleaseTime:
                    type: string
                  dataDisks:
                    items:
                      properties:
                        category:
                          type: string
                        deleteWithInstance:
                          type: boolean
                        description:
                          type: string
                        encrypted:
                          type: boolean
                        name:
                          type: string
                        performanceLevel:
                          type: string
                        size:
                          format: int64
                          type: integer
                        snapshotID:
                          type: string
                      type: object
                    type: array
                  deploymentSetID:
                    type: string
                  description:
                    type: string
                  enableVmOsConfig:
                    type: boolean
                  hostName:
                    type: string
                  id:
                    type: string
                  imageID:
                    type: string
                  imageOwnerAlias:
                    type: string
                  instanceChargeType:
                    type: string
                  instanceName:
                    type: string
                  instanceType:
                    type: string
                  internetChargeType:
                    type: string
                  internetMaxBandwidthIn:
                    format: int64
                    type: integer
                  internetMaxBandwidthOut:
                    format: int64
                    type: integer
                  ioOptimized:
                    type: string
                  keyPairName:
                    type: string
                  launchTemplateName:
                    type: string
                  name:
                    description: Deprecated
                    type: string
                  networkInterfaces:
                    properties:
                      description:
                        type: string
                      name:
                        type: string
                      primaryIP:
                        type: string
                      securityGroupID:
                        type: string
                      vswitchID:
                        type: string
                    type: object
                  networkType:
                    type: string
                  passwordInherit:
                    type: boolean
                  period:
                    format: int64
                    type: integer
                  privateIPAddress:
                    type: string
                  ramRoleName:
                    type: string
                  resourceGroupID:
                    type: string
                  securityEnhancementStrategy:
                    type: string
                  securityGroupID:
                    type: string
                  securityGroupIDS:
                    items:
                      type: string
                    type: array
                  spotDuration:
                    type: string
                  spotPriceLimit:
                    format: double
                    type: number
                  spotStrategy:
                    type: string
                  systemDisk:
                    properties:
                      category:
                        type: string
                      deleteWithInstance:
                        type: boolean
                      description:
                        type: string
                      iops:
                        type: string
                      name:
                        type: string
                      performanceLevel:
                        type: string
                      size:
                        format: int64
                        type: integer
                    type: object
                  systemDiskCategory:
                    description: Deprecated
                    type: string
                  systemDiskDescription:
                    description: Deprecated
                    type: string
                  systemDiskName:
                    description: Deprecated
                    type: string
                  systemDiskSize:
                    description: Deprecated
                    format: int64
                    type: integer
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  templateResourceGroupID:
                    type: string
                  templateTags:
                    additionalProperties:
                      type: string
                    type: object
                  userData:
                    type: string
                  userdata:
                    description: Deprecated
                    type: string
                  versionDescription:
                    type: string
                  vpcID:
                    type: string
                  vswitchID:
                    type: string
                  zoneID:
                    type: string
                type: object
              state:
                properties:
                  autoReleaseTime:
                    type: string
                  dataDisks:
                    items:
                      properties:
                        category:
                          type: string
                        deleteWithInstance:
                          type: boolean
                        description:
                          type: string
                        encrypted:
                          type: boolean
                        name:
                          type: string
                        performanceLevel:
                          type: string
                        size:
                          format: int64
                          type: integer
                        snapshotID:
                          type: string
                      type: object
                    type: array
                  deploymentSetID:
                    type: string
                  description:
                    type: string
                  enableVmOsConfig:
                    type: boolean
                  hostName:
                    type: string
                  id:
                    type: string
                  imageID:
                    type: string
                  imageOwnerAlias:
                    type: string
                  instanceChargeType:
                    type: string
                  instanceName:
                    type: string
                  instanceType:
                    type: string
                  internetChargeType:
                    type: string
                  internetMaxBandwidthIn:
                    format: int64
                    type: integer
                  internetMaxBandwidthOut:
                    format: int64
                    type: integer
                  ioOptimized:
                    type: string
                  keyPairName:
                    type: string
                  launchTemplateName:
                    type: string
                  name:
                    description: Deprecated
                    type: string
                  networkInterfaces:
                    properties:
                      description:
                        type: string
                      name:
                        type: string
                      primaryIP:
                        type: string
                      securityGroupID:
                        type: string
                      vswitchID:
                        type: string
                    type: object
                  networkType:
                    type: string
                  passwordInherit:
                    type: boolean
                  period:
                    format: int64
                    type: integer
                  privateIPAddress:
                    type: string
                  ramRoleName:
                    type: string
                  resourceGroupID:
                    type: string
                  securityEnhancementStrategy:
                    type: string
                  securityGroupID:
                    type: string
                  securityGroupIDS:
                    items:
                      type: string
                    type: array
                  spotDuration:
                    type: string
                  spotPriceLimit:
                    format: double
                    type: number
                  spotStrategy:
                    type: string
                  systemDisk:
                    properties:
                      category:
                        type: string
                      deleteWithInstance:
                        type: boolean
                      description:
                        type: string
                      iops:
                        type: string
                      name:
                        type: string
                      performanceLevel:
                        type: string
                      size:
                        format: int64
                        type: integer
                    type: object
                  systemDiskCategory:
                    description: Deprecated
                    type: string
                  systemDiskDescription:
                    description: Deprecated
                    type: string
                  systemDiskName:
                    description: Deprecated
                    type: string
                  systemDiskSize:
                    description: Deprecated
                    format: int64
                    type: integer
                  tags:
                    additionalProperties:
                      type: string
                    type: object
                  templateResourceGroupID:
                    type: string
                  templateTags:
                    additionalProperties:
                      type: string
                    type: object
                  userData:
                    type: string
                  userdata:
                    description: Deprecated
                    type: string
                  versionDescription:
                    type: string
                  vpcID:
                    type: string
                  vswitchID:
                    type: string
                  zoneID:
                    type: string
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
