/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlertContactListerExpansion allows custom methods to be added to
// AlertContactLister.
type AlertContactListerExpansion interface{}

// AlertContactNamespaceListerExpansion allows custom methods to be added to
// AlertContactNamespaceLister.
type AlertContactNamespaceListerExpansion interface{}

// AlertContactGroupListerExpansion allows custom methods to be added to
// AlertContactGroupLister.
type AlertContactGroupListerExpansion interface{}

// AlertContactGroupNamespaceListerExpansion allows custom methods to be added to
// AlertContactGroupNamespaceLister.
type AlertContactGroupNamespaceListerExpansion interface{}

// DispatchRuleListerExpansion allows custom methods to be added to
// DispatchRuleLister.
type DispatchRuleListerExpansion interface{}

// DispatchRuleNamespaceListerExpansion allows custom methods to be added to
// DispatchRuleNamespaceLister.
type DispatchRuleNamespaceListerExpansion interface{}

// PrometheusAlertRuleListerExpansion allows custom methods to be added to
// PrometheusAlertRuleLister.
type PrometheusAlertRuleListerExpansion interface{}

// PrometheusAlertRuleNamespaceListerExpansion allows custom methods to be added to
// PrometheusAlertRuleNamespaceLister.
type PrometheusAlertRuleNamespaceListerExpansion interface{}
