/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/sag/v1alpha1"
	scheme "kubeform.dev/provider-alicloud-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// QosesGetter has a method to return a QosInterface.
// A group's client should implement this interface.
type QosesGetter interface {
	Qoses(namespace string) QosInterface
}

// QosInterface has methods to work with Qos resources.
type QosInterface interface {
	Create(ctx context.Context, qos *v1alpha1.Qos, opts v1.CreateOptions) (*v1alpha1.Qos, error)
	Update(ctx context.Context, qos *v1alpha1.Qos, opts v1.UpdateOptions) (*v1alpha1.Qos, error)
	UpdateStatus(ctx context.Context, qos *v1alpha1.Qos, opts v1.UpdateOptions) (*v1alpha1.Qos, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Qos, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.QosList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Qos, err error)
	QosExpansion
}

// qoses implements QosInterface
type qoses struct {
	client rest.Interface
	ns     string
}

// newQoses returns a Qoses
func newQoses(c *SagV1alpha1Client, namespace string) *qoses {
	return &qoses{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the qos, and returns the corresponding qos object, and an error if there is any.
func (c *qoses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Qos, err error) {
	result = &v1alpha1.Qos{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("qoses").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Qoses that match those selectors.
func (c *qoses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.QosList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.QosList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("qoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested qoses.
func (c *qoses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("qoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a qos and creates it.  Returns the server's representation of the qos, and an error, if there is any.
func (c *qoses) Create(ctx context.Context, qos *v1alpha1.Qos, opts v1.CreateOptions) (result *v1alpha1.Qos, err error) {
	result = &v1alpha1.Qos{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("qoses").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qos).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a qos and updates it. Returns the server's representation of the qos, and an error, if there is any.
func (c *qoses) Update(ctx context.Context, qos *v1alpha1.Qos, opts v1.UpdateOptions) (result *v1alpha1.Qos, err error) {
	result = &v1alpha1.Qos{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("qoses").
		Name(qos.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qos).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *qoses) UpdateStatus(ctx context.Context, qos *v1alpha1.Qos, opts v1.UpdateOptions) (result *v1alpha1.Qos, err error) {
	result = &v1alpha1.Qos{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("qoses").
		Name(qos.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(qos).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the qos and deletes it. Returns an error if one occurs.
func (c *qoses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("qoses").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *qoses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("qoses").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched qos.
func (c *qoses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Qos, err error) {
	result = &v1alpha1.Qos{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("qoses").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
