/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cs/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKubernetesAutoscalers implements KubernetesAutoscalerInterface
type FakeKubernetesAutoscalers struct {
	Fake *FakeCsV1alpha1
	ns   string
}

var kubernetesautoscalersResource = schema.GroupVersionResource{Group: "cs.alicloud.kubeform.com", Version: "v1alpha1", Resource: "kubernetesautoscalers"}

var kubernetesautoscalersKind = schema.GroupVersionKind{Group: "cs.alicloud.kubeform.com", Version: "v1alpha1", Kind: "KubernetesAutoscaler"}

// Get takes name of the kubernetesAutoscaler, and returns the corresponding kubernetesAutoscaler object, and an error if there is any.
func (c *FakeKubernetesAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.KubernetesAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kubernetesautoscalersResource, c.ns, name), &v1alpha1.KubernetesAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesAutoscaler), err
}

// List takes label and field selectors, and returns the list of KubernetesAutoscalers that match those selectors.
func (c *FakeKubernetesAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.KubernetesAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kubernetesautoscalersResource, kubernetesautoscalersKind, c.ns, opts), &v1alpha1.KubernetesAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KubernetesAutoscalerList{ListMeta: obj.(*v1alpha1.KubernetesAutoscalerList).ListMeta}
	for _, item := range obj.(*v1alpha1.KubernetesAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kubernetesAutoscalers.
func (c *FakeKubernetesAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kubernetesautoscalersResource, c.ns, opts))

}

// Create takes the representation of a kubernetesAutoscaler and creates it.  Returns the server's representation of the kubernetesAutoscaler, and an error, if there is any.
func (c *FakeKubernetesAutoscalers) Create(ctx context.Context, kubernetesAutoscaler *v1alpha1.KubernetesAutoscaler, opts v1.CreateOptions) (result *v1alpha1.KubernetesAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kubernetesautoscalersResource, c.ns, kubernetesAutoscaler), &v1alpha1.KubernetesAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesAutoscaler), err
}

// Update takes the representation of a kubernetesAutoscaler and updates it. Returns the server's representation of the kubernetesAutoscaler, and an error, if there is any.
func (c *FakeKubernetesAutoscalers) Update(ctx context.Context, kubernetesAutoscaler *v1alpha1.KubernetesAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.KubernetesAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kubernetesautoscalersResource, c.ns, kubernetesAutoscaler), &v1alpha1.KubernetesAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesAutoscaler), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKubernetesAutoscalers) UpdateStatus(ctx context.Context, kubernetesAutoscaler *v1alpha1.KubernetesAutoscaler, opts v1.UpdateOptions) (*v1alpha1.KubernetesAutoscaler, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(kubernetesautoscalersResource, "status", c.ns, kubernetesAutoscaler), &v1alpha1.KubernetesAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesAutoscaler), err
}

// Delete takes name of the kubernetesAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeKubernetesAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kubernetesautoscalersResource, c.ns, name), &v1alpha1.KubernetesAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKubernetesAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kubernetesautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.KubernetesAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched kubernetesAutoscaler.
func (c *FakeKubernetesAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.KubernetesAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kubernetesautoscalersResource, c.ns, name, pt, data, subresources...), &v1alpha1.KubernetesAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KubernetesAutoscaler), err
}
