/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/security/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCenterServiceLinkedRoles implements CenterServiceLinkedRoleInterface
type FakeCenterServiceLinkedRoles struct {
	Fake *FakeSecurityV1alpha1
	ns   string
}

var centerservicelinkedrolesResource = schema.GroupVersionResource{Group: "security.alicloud.kubeform.com", Version: "v1alpha1", Resource: "centerservicelinkedroles"}

var centerservicelinkedrolesKind = schema.GroupVersionKind{Group: "security.alicloud.kubeform.com", Version: "v1alpha1", Kind: "CenterServiceLinkedRole"}

// Get takes name of the centerServiceLinkedRole, and returns the corresponding centerServiceLinkedRole object, and an error if there is any.
func (c *FakeCenterServiceLinkedRoles) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CenterServiceLinkedRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(centerservicelinkedrolesResource, c.ns, name), &v1alpha1.CenterServiceLinkedRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CenterServiceLinkedRole), err
}

// List takes label and field selectors, and returns the list of CenterServiceLinkedRoles that match those selectors.
func (c *FakeCenterServiceLinkedRoles) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CenterServiceLinkedRoleList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(centerservicelinkedrolesResource, centerservicelinkedrolesKind, c.ns, opts), &v1alpha1.CenterServiceLinkedRoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CenterServiceLinkedRoleList{ListMeta: obj.(*v1alpha1.CenterServiceLinkedRoleList).ListMeta}
	for _, item := range obj.(*v1alpha1.CenterServiceLinkedRoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested centerServiceLinkedRoles.
func (c *FakeCenterServiceLinkedRoles) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(centerservicelinkedrolesResource, c.ns, opts))

}

// Create takes the representation of a centerServiceLinkedRole and creates it.  Returns the server's representation of the centerServiceLinkedRole, and an error, if there is any.
func (c *FakeCenterServiceLinkedRoles) Create(ctx context.Context, centerServiceLinkedRole *v1alpha1.CenterServiceLinkedRole, opts v1.CreateOptions) (result *v1alpha1.CenterServiceLinkedRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(centerservicelinkedrolesResource, c.ns, centerServiceLinkedRole), &v1alpha1.CenterServiceLinkedRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CenterServiceLinkedRole), err
}

// Update takes the representation of a centerServiceLinkedRole and updates it. Returns the server's representation of the centerServiceLinkedRole, and an error, if there is any.
func (c *FakeCenterServiceLinkedRoles) Update(ctx context.Context, centerServiceLinkedRole *v1alpha1.CenterServiceLinkedRole, opts v1.UpdateOptions) (result *v1alpha1.CenterServiceLinkedRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(centerservicelinkedrolesResource, c.ns, centerServiceLinkedRole), &v1alpha1.CenterServiceLinkedRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CenterServiceLinkedRole), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCenterServiceLinkedRoles) UpdateStatus(ctx context.Context, centerServiceLinkedRole *v1alpha1.CenterServiceLinkedRole, opts v1.UpdateOptions) (*v1alpha1.CenterServiceLinkedRole, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(centerservicelinkedrolesResource, "status", c.ns, centerServiceLinkedRole), &v1alpha1.CenterServiceLinkedRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CenterServiceLinkedRole), err
}

// Delete takes name of the centerServiceLinkedRole and deletes it. Returns an error if one occurs.
func (c *FakeCenterServiceLinkedRoles) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(centerservicelinkedrolesResource, c.ns, name), &v1alpha1.CenterServiceLinkedRole{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCenterServiceLinkedRoles) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(centerservicelinkedrolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CenterServiceLinkedRoleList{})
	return err
}

// Patch applies the patch and returns the patched centerServiceLinkedRole.
func (c *FakeCenterServiceLinkedRoles) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CenterServiceLinkedRole, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(centerservicelinkedrolesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CenterServiceLinkedRole{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CenterServiceLinkedRole), err
}
