/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AcceleratorListerExpansion allows custom methods to be added to
// AcceleratorLister.
type AcceleratorListerExpansion interface{}

// AcceleratorNamespaceListerExpansion allows custom methods to be added to
// AcceleratorNamespaceLister.
type AcceleratorNamespaceListerExpansion interface{}

// AclListerExpansion allows custom methods to be added to
// AclLister.
type AclListerExpansion interface{}

// AclNamespaceListerExpansion allows custom methods to be added to
// AclNamespaceLister.
type AclNamespaceListerExpansion interface{}

// AclAttachmentListerExpansion allows custom methods to be added to
// AclAttachmentLister.
type AclAttachmentListerExpansion interface{}

// AclAttachmentNamespaceListerExpansion allows custom methods to be added to
// AclAttachmentNamespaceLister.
type AclAttachmentNamespaceListerExpansion interface{}

// AdditionalCertificateListerExpansion allows custom methods to be added to
// AdditionalCertificateLister.
type AdditionalCertificateListerExpansion interface{}

// AdditionalCertificateNamespaceListerExpansion allows custom methods to be added to
// AdditionalCertificateNamespaceLister.
type AdditionalCertificateNamespaceListerExpansion interface{}

// BandwidthPackageListerExpansion allows custom methods to be added to
// BandwidthPackageLister.
type BandwidthPackageListerExpansion interface{}

// BandwidthPackageNamespaceListerExpansion allows custom methods to be added to
// BandwidthPackageNamespaceLister.
type BandwidthPackageNamespaceListerExpansion interface{}

// BandwidthPackageAttachmentListerExpansion allows custom methods to be added to
// BandwidthPackageAttachmentLister.
type BandwidthPackageAttachmentListerExpansion interface{}

// BandwidthPackageAttachmentNamespaceListerExpansion allows custom methods to be added to
// BandwidthPackageAttachmentNamespaceLister.
type BandwidthPackageAttachmentNamespaceListerExpansion interface{}

// EndpointGroupListerExpansion allows custom methods to be added to
// EndpointGroupLister.
type EndpointGroupListerExpansion interface{}

// EndpointGroupNamespaceListerExpansion allows custom methods to be added to
// EndpointGroupNamespaceLister.
type EndpointGroupNamespaceListerExpansion interface{}

// ForwardingRuleListerExpansion allows custom methods to be added to
// ForwardingRuleLister.
type ForwardingRuleListerExpansion interface{}

// ForwardingRuleNamespaceListerExpansion allows custom methods to be added to
// ForwardingRuleNamespaceLister.
type ForwardingRuleNamespaceListerExpansion interface{}

// IpSetListerExpansion allows custom methods to be added to
// IpSetLister.
type IpSetListerExpansion interface{}

// IpSetNamespaceListerExpansion allows custom methods to be added to
// IpSetNamespaceLister.
type IpSetNamespaceListerExpansion interface{}

// ListenerListerExpansion allows custom methods to be added to
// ListenerLister.
type ListenerListerExpansion interface{}

// ListenerNamespaceListerExpansion allows custom methods to be added to
// ListenerNamespaceLister.
type ListenerNamespaceListerExpansion interface{}
