/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BridgeEventBusListerExpansion allows custom methods to be added to
// BridgeEventBusLister.
type BridgeEventBusListerExpansion interface{}

// BridgeEventBusNamespaceListerExpansion allows custom methods to be added to
// BridgeEventBusNamespaceLister.
type BridgeEventBusNamespaceListerExpansion interface{}

// BridgeEventSourceListerExpansion allows custom methods to be added to
// BridgeEventSourceLister.
type BridgeEventSourceListerExpansion interface{}

// BridgeEventSourceNamespaceListerExpansion allows custom methods to be added to
// BridgeEventSourceNamespaceLister.
type BridgeEventSourceNamespaceListerExpansion interface{}

// BridgeRuleListerExpansion allows custom methods to be added to
// BridgeRuleLister.
type BridgeRuleListerExpansion interface{}

// BridgeRuleNamespaceListerExpansion allows custom methods to be added to
// BridgeRuleNamespaceLister.
type BridgeRuleNamespaceListerExpansion interface{}

// BridgeServiceLinkedRoleListerExpansion allows custom methods to be added to
// BridgeServiceLinkedRoleLister.
type BridgeServiceLinkedRoleListerExpansion interface{}

// BridgeServiceLinkedRoleNamespaceListerExpansion allows custom methods to be added to
// BridgeServiceLinkedRoleNamespaceLister.
type BridgeServiceLinkedRoleNamespaceListerExpansion interface{}

// BridgeSlrListerExpansion allows custom methods to be added to
// BridgeSlrLister.
type BridgeSlrListerExpansion interface{}

// BridgeSlrNamespaceListerExpansion allows custom methods to be added to
// BridgeSlrNamespaceLister.
type BridgeSlrNamespaceListerExpansion interface{}
