/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AlarmListerExpansion allows custom methods to be added to
// AlarmLister.
type AlarmListerExpansion interface{}

// AlarmNamespaceListerExpansion allows custom methods to be added to
// AlarmNamespaceLister.
type AlarmNamespaceListerExpansion interface{}

// AlbServerGroupAttachmentListerExpansion allows custom methods to be added to
// AlbServerGroupAttachmentLister.
type AlbServerGroupAttachmentListerExpansion interface{}

// AlbServerGroupAttachmentNamespaceListerExpansion allows custom methods to be added to
// AlbServerGroupAttachmentNamespaceLister.
type AlbServerGroupAttachmentNamespaceListerExpansion interface{}

// AttachmentListerExpansion allows custom methods to be added to
// AttachmentLister.
type AttachmentListerExpansion interface{}

// AttachmentNamespaceListerExpansion allows custom methods to be added to
// AttachmentNamespaceLister.
type AttachmentNamespaceListerExpansion interface{}

// LifecycleHookListerExpansion allows custom methods to be added to
// LifecycleHookLister.
type LifecycleHookListerExpansion interface{}

// LifecycleHookNamespaceListerExpansion allows custom methods to be added to
// LifecycleHookNamespaceLister.
type LifecycleHookNamespaceListerExpansion interface{}

// NotificationListerExpansion allows custom methods to be added to
// NotificationLister.
type NotificationListerExpansion interface{}

// NotificationNamespaceListerExpansion allows custom methods to be added to
// NotificationNamespaceLister.
type NotificationNamespaceListerExpansion interface{}

// ScalingConfigurationListerExpansion allows custom methods to be added to
// ScalingConfigurationLister.
type ScalingConfigurationListerExpansion interface{}

// ScalingConfigurationNamespaceListerExpansion allows custom methods to be added to
// ScalingConfigurationNamespaceLister.
type ScalingConfigurationNamespaceListerExpansion interface{}

// ScalingGroupListerExpansion allows custom methods to be added to
// ScalingGroupLister.
type ScalingGroupListerExpansion interface{}

// ScalingGroupNamespaceListerExpansion allows custom methods to be added to
// ScalingGroupNamespaceLister.
type ScalingGroupNamespaceListerExpansion interface{}

// ScalingRuleListerExpansion allows custom methods to be added to
// ScalingRuleLister.
type ScalingRuleListerExpansion interface{}

// ScalingRuleNamespaceListerExpansion allows custom methods to be added to
// ScalingRuleNamespaceLister.
type ScalingRuleNamespaceListerExpansion interface{}

// ScalinggroupVserverGroupsListerExpansion allows custom methods to be added to
// ScalinggroupVserverGroupsLister.
type ScalinggroupVserverGroupsListerExpansion interface{}

// ScalinggroupVserverGroupsNamespaceListerExpansion allows custom methods to be added to
// ScalinggroupVserverGroupsNamespaceLister.
type ScalinggroupVserverGroupsNamespaceListerExpansion interface{}

// ScheduleListerExpansion allows custom methods to be added to
// ScheduleLister.
type ScheduleListerExpansion interface{}

// ScheduleNamespaceListerExpansion allows custom methods to be added to
// ScheduleNamespaceLister.
type ScheduleNamespaceListerExpansion interface{}

// ScheduledTaskListerExpansion allows custom methods to be added to
// ScheduledTaskLister.
type ScheduledTaskListerExpansion interface{}

// ScheduledTaskNamespaceListerExpansion allows custom methods to be added to
// ScheduledTaskNamespaceLister.
type ScheduledTaskNamespaceListerExpansion interface{}
