/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/resource/v1alpha1"
	scheme "kubeform.dev/provider-alicloud-api/client/clientset/versioned/scheme"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManagerResourceSharesGetter has a method to return a ManagerResourceShareInterface.
// A group's client should implement this interface.
type ManagerResourceSharesGetter interface {
	ManagerResourceShares(namespace string) ManagerResourceShareInterface
}

// ManagerResourceShareInterface has methods to work with ManagerResourceShare resources.
type ManagerResourceShareInterface interface {
	Create(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.CreateOptions) (*v1alpha1.ManagerResourceShare, error)
	Update(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.UpdateOptions) (*v1alpha1.ManagerResourceShare, error)
	UpdateStatus(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.UpdateOptions) (*v1alpha1.ManagerResourceShare, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ManagerResourceShare, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ManagerResourceShareList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagerResourceShare, err error)
	ManagerResourceShareExpansion
}

// managerResourceShares implements ManagerResourceShareInterface
type managerResourceShares struct {
	client rest.Interface
	ns     string
}

// newManagerResourceShares returns a ManagerResourceShares
func newManagerResourceShares(c *ResourceV1alpha1Client, namespace string) *managerResourceShares {
	return &managerResourceShares{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the managerResourceShare, and returns the corresponding managerResourceShare object, and an error if there is any.
func (c *managerResourceShares) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ManagerResourceShare, err error) {
	result = &v1alpha1.ManagerResourceShare{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managerresourceshares").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManagerResourceShares that match those selectors.
func (c *managerResourceShares) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ManagerResourceShareList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ManagerResourceShareList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("managerresourceshares").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested managerResourceShares.
func (c *managerResourceShares) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("managerresourceshares").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a managerResourceShare and creates it.  Returns the server's representation of the managerResourceShare, and an error, if there is any.
func (c *managerResourceShares) Create(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.CreateOptions) (result *v1alpha1.ManagerResourceShare, err error) {
	result = &v1alpha1.ManagerResourceShare{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("managerresourceshares").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managerResourceShare).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a managerResourceShare and updates it. Returns the server's representation of the managerResourceShare, and an error, if there is any.
func (c *managerResourceShares) Update(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.UpdateOptions) (result *v1alpha1.ManagerResourceShare, err error) {
	result = &v1alpha1.ManagerResourceShare{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managerresourceshares").
		Name(managerResourceShare.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managerResourceShare).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *managerResourceShares) UpdateStatus(ctx context.Context, managerResourceShare *v1alpha1.ManagerResourceShare, opts v1.UpdateOptions) (result *v1alpha1.ManagerResourceShare, err error) {
	result = &v1alpha1.ManagerResourceShare{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("managerresourceshares").
		Name(managerResourceShare.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(managerResourceShare).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the managerResourceShare and deletes it. Returns an error if one occurs.
func (c *managerResourceShares) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managerresourceshares").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *managerResourceShares) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("managerresourceshares").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched managerResourceShare.
func (c *managerResourceShares) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ManagerResourceShare, err error) {
	result = &v1alpha1.ManagerResourceShare{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("managerresourceshares").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
