/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubeform.dev/provider-alicloud-api/apis/cs/v1alpha1"
	"kubeform.dev/provider-alicloud-api/client/clientset/versioned/scheme"

	rest "k8s.io/client-go/rest"
)

type CsV1alpha1Interface interface {
	RESTClient() rest.Interface
	ApplicationsGetter
	AutoscalingConfigsGetter
	EdgeKubernetesesGetter
	KubernetesesGetter
	KubernetesAutoscalersGetter
	KubernetesNodePoolsGetter
	KubernetesPermissionsesGetter
	ManagedKubernetesesGetter
	ServerlessKubernetesesGetter
	SwarmsGetter
}

// CsV1alpha1Client is used to interact with features provided by the cs.alicloud.kubeform.com group.
type CsV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CsV1alpha1Client) Applications(namespace string) ApplicationInterface {
	return newApplications(c, namespace)
}

func (c *CsV1alpha1Client) AutoscalingConfigs(namespace string) AutoscalingConfigInterface {
	return newAutoscalingConfigs(c, namespace)
}

func (c *CsV1alpha1Client) EdgeKuberneteses(namespace string) EdgeKubernetesInterface {
	return newEdgeKuberneteses(c, namespace)
}

func (c *CsV1alpha1Client) Kuberneteses(namespace string) KubernetesInterface {
	return newKuberneteses(c, namespace)
}

func (c *CsV1alpha1Client) KubernetesAutoscalers(namespace string) KubernetesAutoscalerInterface {
	return newKubernetesAutoscalers(c, namespace)
}

func (c *CsV1alpha1Client) KubernetesNodePools(namespace string) KubernetesNodePoolInterface {
	return newKubernetesNodePools(c, namespace)
}

func (c *CsV1alpha1Client) KubernetesPermissionses(namespace string) KubernetesPermissionsInterface {
	return newKubernetesPermissionses(c, namespace)
}

func (c *CsV1alpha1Client) ManagedKuberneteses(namespace string) ManagedKubernetesInterface {
	return newManagedKuberneteses(c, namespace)
}

func (c *CsV1alpha1Client) ServerlessKuberneteses(namespace string) ServerlessKubernetesInterface {
	return newServerlessKuberneteses(c, namespace)
}

func (c *CsV1alpha1Client) Swarms(namespace string) SwarmInterface {
	return newSwarms(c, namespace)
}

// NewForConfig creates a new CsV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CsV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CsV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CsV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CsV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CsV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CsV1alpha1Client {
	return &CsV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CsV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
